### ISSUE TITLE
Data Directory needed on startup

### ISSUE THREAD

**Issue by btcforplebs** [kibo-money/kibo#4]
Hello, on initial start up I would like to use a bitcoin directory on other host. (Other than local host) 

the _datadir =_ does not appear to allow for this, or maybe it does and I'm just missing a piece to the puzzle 

Could you provide a little more clarity as to the formatting for this datadir = field?

**Comment by drgarlic** [comment]
Hi !

So `--datadir` is the path to the bitcoin folder, the same path you give to `bitcoind`

If you wanna pass an IP for the RPC calls, you should instead give it to the `--rpcconnect` parameter

**Comment by btcforplebs** [comment]
That's makes sense.
However, In order to run the parser, I do need to set that directive at least once. (That's the message it's giving when I try to run)

Your saying, provide it with the folder path of that host
ie.. 
for embassy -  /embassy-data/package-data/volumes/bitcoind/data/main/

For MyNode - /mnt/hdd/mynode/bitcoin

Am I correct in that?

**Comment by drgarlic** [comment]
Yes ! You need it once as it's saved in a `config.toml` file and it's needed to parse the `blockXXX.dat` files

It looks correct yes, basically it's the path to the folder that contains the `blocks`, `chainstate` and `indexes` folders

**Comment by btcforplebs** [comment]
Thanks for the direction! I'll keep trying to perfect the config.toml file to get connected. Looks like my local nodes have weird ports and firewalls.

Thanks for the clarification on what directories it's looking for. I'm excited to see how this project progresses!

**Comment by drgarlic** [comment]
If you need any help don't hesitate to ask here or on Nostr !
