### ISSUE TITLE
Running Locally with --rpccookiefile

### ISSUE THREAD

**Issue by xjmzx** [kibo-money/kibo#6]
Hey just trying to get this running locally and want to ask is` --rpcuser` `--rpcpassword` a requirement? All my setups specifiy `--rpccookiefile` 
I could change for testing but just wanted to ask about this before I change any settings on systemd / electrs etc.

I see from the help there is no option

```
      --datadir <DIR>              Bitcoin data directory path, saved
      --rpcconnect <IP>            Bitcoin RPC ip, default: localhost, saved
      --rpcport <PORT>             Bitcoin RPC port, default: 8332, saved
      --rpcuser <USERNAME>         Bitcoin RPC username, saved
      --rpcpassword <PASSWORD>     Bitcoin RPC password, saved
      --delay <SECONDS>            Delay between runs, default: 0, saved
      --dry-run <BOOL>             Start a dry run, default: false, not saved [possible values: true, false]
      --record-ram-usage <BOOL>    Record ram usage, default: false, not saved [possible values: true, false]
      --recompute-computed <BOOL>  Recompute all computed datasets, default: false, not saved [possible values: true, false]
      --first-defragment <BOOL>    Start the program by defragmenting all databases to reduce their footprint, default: false, not saved [possible values: true, false]
  -h, --help                       Print help
  -V, --version  
```

Might this be implimented in future?

**Comment by drgarlic** [comment]
Hi !

Just fixed it for you 👍, you can specify it now but it will auto find it if the path is `--datadir/.cookie`

**Comment by xjmzx** [comment]
Thanks, that is now working. At the moment, the parser is doing it's thing.
If I have any questions, is it best to open an issue or is there any place for discussion?

Appreciate you doing that. I'm going to close this.
